"""create_tables

Revision ID: 87fed69f8f76
Revises: b6f6760a57d2
Create Date: 2023-08-08 15:08:57.554133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87fed69f8f76'
down_revision = 'b6f6760a57d2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
