"""Add Users

Revision ID: b6f6760a57d2
Revises: 2a9dc60d4024
Create Date: 2023-08-08 12:15:13.842653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6f6760a57d2'
down_revision = '2a9dc60d4024'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
